docker/bcctapp/urls.py
from django.urls import path
from .views import PatientDetailView, PatientCreateView, PatientUpdateView, PatientDeleteView, UserPatientListView, \
    ImagePatientUpdateView, PatientSharedDetailView, InteractionsDetailView, TeamsCreateView, \
    MyTeamsListView,TeamListView
from . import views
from django.conf.urls import include



urlpatterns = [
    path('', views.bcctapphome, name='bcctapp-home'),
    path('contact/', views.contact, name='bcctapp-contact'),
    # path('chat/', views.chat, name='bcctapp-chat'),
    path('patient/<int:pk>/', PatientDetailView.as_view(), name='patient-detail'),
    path('team/', TeamsCreateView.as_view(), name='teams-detail'), #done
    path('my_teams/', TeamListView.as_view(), name='my-teams'), #done
    path('myteam/<str:name>', MyTeamsListView.as_view(), name='my-team'), #done
    path('patient/new/', PatientCreateView.as_view(), name='patient-new'), #done
    path('patient/shared/<int:pk>', PatientSharedDetailView.as_view(), name='patient-shared'), #not used
    path('patient/<int:pk>/update/', PatientUpdateView.as_view(), name='patient-update'), #done
    path('patient/<int:pk>/update-image/', ImagePatientUpdateView.as_view(), name='patient-update-image'), #done
    path('patient/<int:pk>/delete/', PatientDeleteView.as_view(), name='patient-delete'), #done
    path('image/<int:pk>/<int>/', InteractionsDetailView.as_view(), name='interaction-form'), #done
    path('user/<str:username>', UserPatientListView.as_view(), name='user-patient'), #done
    path('about/', views.about, name='bcctapp-about'), #done (repetida)
    #path('medical_image_upload/', views.upload_medical_image, name='medical-image-upload'),
    #path('medical_image_modal', views.medical_image_modal, name='medical-image-modal'),
    #path('medical_image_modal/<int:pk>/<int>/', views.medical_image_modal, name='medical-image-modal'),
    path('model/<int:pk>/<int>/', views.medical_image_modal, name='model'), #cant do anything
    path('plot/<int:pk>/<int>/', views.plot_image_modal, name='plot'), #envia me po bcctcore
    path('bcctcore/<int:pk>/<int>/', views.bcctcore, name='bcctcore'),
    path('bcctcore/updateBra/', views.update_breast_bra, name='update_breast_bra'),
    path('patient/images/download', views.download_image, name = 'download-images'),
    path('export/excel', views.export_users_xls, name='export-excel')
    
]

docker/chat/urls.py
from django.urls import path
from . import views
from .views import GroupCreateView, GroupUpdateView

app_name = 'chat'

urlpatterns = [
    path('room/<int:room_name>/', views.ShowChatPage, name = "show-chat"),
    path('room/', views.ShowChatPage, kwargs={'room_name': None}, name = "show-chat"),
    path('room/new/', GroupCreateView.as_view(), name = "group-create"),
    path('room/<int:pk>/update/', GroupUpdateView.as_view(), name = "group-update"),
    path('get/ajax/loadMessages/', views.loadMessage, name = "load-messages")


]

docker/webbcct/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bcctapp.urls')),
    path('cinderella/', include('cinderella.urls')), 
    path('register/', user_views.register, name="register"),
    path('profile/', user_views.profile, name="profile"), #done
    path('accounts/',include('allauth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),
    path('chat/', include('chat.urls', namespace = 'chat')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docker/chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from bcctapp.models import Teams
from django.urls import reverse

class Group(models.Model):
    name = models.CharField(null=False, max_length = 64)
    team = models.ForeignKey(Teams, on_delete=models.CASCADE)

    def __str__(self):
        return "name is {} and its id is {}".format(self.name, self.team.id)
    
    def get_absolute_url(self):
        return reverse("chat:show-chat", kwargs = {'room_name':self.pk})



class Message(models.Model):
    author = models.ForeignKey(get_user_model(), related_name = 'author_messages', on_delete = models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add = True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE) 


    def __str__(self):
        return self.author.username

    

docker/bcctapp/forms.py
from django import forms
from .models import Photo, MedicalImages, Patient, ImagesPatient, InteractionsPatient, Teams
import datetime

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file',)


class FileFieldForm(forms.Form):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))


class MedicalImagesForm(forms.ModelForm):
    class Meta:
        model = MedicalImages
        fields = ('image',)

class DateInput(forms.DateInput):
    input_type = 'date'

class PatientForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    age = forms.IntegerField(min_value=0)
    birthday = forms.DateField(input_formats=['%d/%m/%Y'],widget = DateInput)
    surgery_date = forms.DateField(input_formats=['%d/%m/%Y'],widget = DateInput)
    patient_height = forms.IntegerField(min_value=1)
    patient_weight = forms.IntegerField(min_value=1)
    bra=forms.CharField(max_length=100)
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Patient
        fields = ('first_name','last_name','images','age','patient_weight','patient_height','bra','surgery_type','surgery_date','birthday',)

class ImagesForm(forms.ModelForm):
    image = forms.ModelMultipleChoiceField(queryset=Patient.objects.all())

    class Meta:
        model = ImagesPatient
        fields = ('image',)

class InteractionsPatientForm(forms.ModelForm):
    number = forms.IntegerField()
    interaction_type = forms.IntegerField()

    class Meta:
        model = InteractionsPatient
        fields = ('number','interaction_type',)

class TeamsForm(forms.ModelForm):
    name = forms.CharField(max_length=100)
    users = forms.CharField(max_length=100)
    patients = forms.CharField(max_length=100)

    class Meta:
        model = Teams
        fields = ('name','users',)


class ContactForm(forms.Form):
    name = forms.CharField(required = True)
    email = forms.EmailField(required = True)
    content = forms.CharField(required = False, max_length=1024, widget=forms.Textarea(attrs={"rows":6, "cols":20}))
    CHOICES = (('1', '',), ('2', '',),('3', '',), ('4', '',),('5',''))
    score = forms.ChoiceField(required = True, widget=forms.RadioSelect, choices=CHOICES)

docker/bcctapp/views.py
import tensorflow
import subprocess
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect, request
from .models import Patient, Photo, MedicalImages, ImagesPatient, InteractionsPatient, Teams
from .forms import PhotoForm, MedicalImagesForm, PatientForm, ImagesForm, InteractionsPatientForm, TeamsForm, ContactForm
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.files.storage import FileSystemStorage, default_storage
from utils.utils import keypoint_prediction
import datetime
import numpy as np
import platform
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic.edit import FormView
from django.contrib.auth.models import User
import datetime
from datetime import datetime
import exifread
import PIL.Image
import PIL.ExifTags
from PIL.ExifTags import TAGS
import cv2
import psutil
import sched
import time
from django.template.loader import get_template
from email.message import EmailMessage
from django.core.mail import send_mail
from django.conf import settings
from .filters import PatientFilter, TeamFilter
from django.http import JsonResponse, HttpResponseNotFound
import os
import zipfile
from django.contrib import messages
from io import BytesIO
from django_filters.views import FilterView
import xlwt
import csv


scheduler = sched.scheduler(time.time, time.sleep)


def surgeryTypeConverterXLSX(i):
    switcher={
        1: "Conservative surgery - unilateral",
        2: "Conservative surgery with bilateral reduction",
        3: "Conservative surgery with LD or LICAP / TDAP ",
        4: "Mastectomy with unilateral reconstruction with implant",
        5: "Mastectomy with unilateral reconstruction with autologous flap",
        6: "Mastectomy with bilateral reconstruction with implants",
        7: "Mastectomy with unilateral reconstruction with implant and contralateral symmetrization with implant(augmentation)",
        8: "Mastectomy with unilateral reconstruction with implant and contralateral symmetrization with reduction",
        9: "Mastectomy with unilateral reconstruction with autologous flap and contralateral symmetrization with reduction",
        10: "Mastectomy with unilateral reconstruction with autologous flap and contralateral symmetrisation with implant(augmentation)",
    }
    return switcher.get(i, "NULL")


def surgeryTypeConverterCSV(i):
    switcher = {
        '1': "Conservative surgery - unilateral",
        '2': "Conservative surgery with bilateral reduction",
        '3': "Conservative surgery with LD or LICAP / TDAP ",
        '4': "Mastectomy with unilateral reconstruction with implant",
        '5': "Mastectomy with unilateral reconstruction with autologous flap",
        '6': "Mastectomy with bilateral reconstruction with implants",
        '7': "Mastectomy with unilateral reconstruction with implant and contralateral symmetrization with implant(augmentation)",
        '8': "Mastectomy with unilateral reconstruction with implant and contralateral symmetrization with reduction",
        '9': "Mastectomy with unilateral reconstruction with autologous flap and contralateral symmetrization with reduction",
        '10': "Mastectomy with unilateral reconstruction with autologous flap and contralateral symmetrisation with implant(augmentation)",
    }
    return switcher.get(i, "NULL")


def export_users_xls(request):

    if request.method == "POST":
        patient_id = request.POST.get('patient_id')
        if request.POST.get('export-type') == 'xlsx':
            response = HttpResponse(content_type='application/ms-excel')
            response['Content-Disposition'] = 'attachment; filename="PatientInfo.xls"'

            wb = xlwt.Workbook(encoding='utf-8')
        # this will make a sheet named Users Data
            ws = wb.add_sheet('Patient Data')

        # Sheet header, first row
            row_num = 0

            font_style = xlwt.XFStyle()
            font_style.font.bold = True

            columns = ['ID', 'First Name', 'Last Name',
                    'Age', 'Weight', 'Height', 'Bra', 'Team', 'Surgery Type', ]

            for col_num in range(len(columns)):
                # at 0 row 0 column
                ws.write(row_num, col_num, columns[col_num], font_style)

            # Sheet body, remaining rows
            font_style = xlwt.XFStyle()

            rows = Patient.objects.filter(pk=patient_id).values_list(
                'id', 'first_name', 'last_name', 'age', 'patient_weight', 'patient_height', 'bra', 'team', 'surgery_type')
            for row in rows:
                row_num += 1
                for col_num in range(len(row)):
                    if col_num == 8:
                        converted_surgery_type = surgeryTypeConverterXLSX(row[col_num])
                        ws.write(row_num, col_num, converted_surgery_type, font_style)
                    else:
                        ws.write(row_num, col_num, row[col_num], font_style)

            wb.save(response)

            return response

        elif request.POST.get('export-type') == 'csv':
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="PatientInfo.csv"'

            writer = csv.writer(response)

            columns = ['ID', 'First Name', 'Last Name',
                       'Age', 'Weight', 'Height', 'Bra', 'Team', 'Surgery Type', ]
            
            writer.writerow(columns)

            rows = Patient.objects.filter(pk=patient_id).values_list(
                'id', 'first_name', 'last_name', 'age', 'patient_weight', 'patient_height', 'bra', 'team', 'surgery_type')
            conv_rows = np.asarray(rows)

            for row in conv_rows:
                row[8] = surgeryTypeConverterCSV(row[8])
                writer.writerow(row)

            return response

        return HttpResponseRedirect('/patient/' + patient_id)

    return HttpResponseNotFound('<h1>Invalid request</h1>')


def download_image(request):
    if request.method == "POST":
        patient_id = request.POST.get('patient_id')

        product_images = ImagesPatient.objects.filter(pk=patient_id)

        if product_images.count() == 0:
            return JsonResponse({"message": "No images available to download"})

        filenames = []
        for product_image in product_images:
            filenames.append(str(product_image.image.file))

        # if size is 0 then does nothing
        if len(filenames) == 0:
            messages.add_message(request, messages.INFO, 'No images available')
            return HttpResponseRedirect('/patient/' + patient_id)

        # change
        zip_subdir = "patient_" + patient_id + "_images"
        zip_filename = "%s.zip" % zip_subdir

        s = BytesIO()

        # The zip compressor
        zf = zipfile.ZipFile(s, "w")

        for fpath in filenames:
            # Calculate path for file in zip
            fdir, fname = os.path.split(fpath)
            zip_path = os.path.join(zip_subdir, fname)

            # Add file, at correct path
            zf.write(fpath, zip_path)

        # Must close zip for all contents to be written
        zf.close()
        resp = HttpResponse(
            s.getvalue(), content_type="application/x-zip-compressed")
        resp['Content-Disposition'] = 'attachment; filename=%s' % zip_filename
        return resp

    #messages.error(request, 'Invalid request')
    return HttpResponseNotFound('<h1>Invalid request</h1>')


def print_event(name):
    print('EVENT:', time.time(), name)


# Create your views here.


def bcctapphome(request):
    return render(request, 'bcctapp/about.html')
    # return HttpResponse('<h1>BCCTApp Home</h1>')


def get_exif(fn):
    infoDict = {}  # Creating the dict to get the metadata tags

    # For mac and linux user it is just
    exifToolPath = "exiftool"

    imgPath = "/code/media/medical_images4/" + str(fn)

    ''' use Exif tool to get the metadata '''
    process = subprocess.Popen([exifToolPath, imgPath], stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                               universal_newlines=True)
    ''' get the tags in dict '''
    for tag in process.stdout:
        line = tag.strip().split(':')
        infoDict[line[0].strip()] = line[-1].strip()

    return infoDict


class MyTeamsListView(FormView):
    form_class = TeamsForm
    template_name = 'bcctapp/my_team.html'  # Replace with your template.
    success_url = 'my-team'
    print("agora sim")

    def get_context_data(self, request=None, **kwargs):
        print("kw", **kwargs)
        print("self", self.kwargs.get('name'))
        context = super(MyTeamsListView, self).get_context_data(**kwargs)
        teams = Teams.objects.get(name=self.kwargs.get('name'))
        print("teams.id", teams.id)
        context['patient'] = Patient.objects.filter(team=teams.id)
        context['team_id'] = teams.id
        #print("list", list)
        # return render(request, "bcctapp/my_team.html", {'list': list1})
        return context

    def post(self, request, *args, **kwargs):
        print("agora sim tou no post")


class TeamsCreateView(FormView):
    form_class = TeamsForm
    template_name = 'bcctapp/teams.html'  # Replace with your template.
    success_url = 'teams-detail'

    def post(self, request, *args, **kwargs):
        user_id = request.POST.get('user_id')
        name_team = request.POST.get('name_team')
        name = request.POST.get('name')
        print("name", name)
        count = Teams.objects.all().count()
        id_string = " " + str(user_id)
        print(type(id_string))

docker/bcctapp/templates/bcctapp/about.html
{% extends "bcctapp/base.html" %}
{% block content %}
    <h1>About WebBCCT.core</h1><br>
    <p style="text-align: justify">Breast cancer conservative treatment (BCCT) has been increasingly used over the last few years, as a consequence of its oncological safety and much more acceptable aesthetic outcome.</p>
    <p style="text-align: justify">Although considerable research has been put into BCCT results and techniques, the aesthetic results are commonly heterogeneous.</p>
    <p style="text-align: justify">Traditionally, aesthetic evaluation has been performed subjectively by one or more observers. However, this form of assessment has been proved to be not only time consuming but also poorly reproducible. Objective methods of evaluation emerged as a way to overcome the poor reproducibility of subjective assessment.</p>
    <p style="text-align: justify">The purpose of the WebBCCT.core (Web Breast Cancer Conservative Treatment.cosmetic results) software is to try to simplify and standardise the aesthetical evaluation of BCCT. Its innovative nature consists on the development of a totally objective tool for the quantification of the aesthetic results in BCCT, discriminating between four categories (excellent, good, fair and poor) of overall subjective evaluation.</p>
    <p style="text-align: justify">The WebBCCT.core Workstation allows the user to select one of the available medical images from an image database. This database may include one to four images of the same patient, comprising front (arms up and down) and lateral views of the patient. The selected images are displayed on the monitor screen of the user computer.
    The WebBCCT.core Workstation integrates a tool to quickly and accurately automate the measurement process of all the well-known indices correlated with the overall aesthetical result of the breast cancer conservative treatment. Users will find WebBCCT.core especially useful for reporting quickly and accurately results that were, up until now, time consuming, requiring the proficiency on several tools. 
    A second major functionality of WebBCCT.core Workstation is the capability to translate automatically the set of measures performed on the digital images onto an overall objective classification of the aesthetical result. The objective overall classification outputted by this module constitutes a valuable summary of the aesthetical result, enabling effective comparison among different medical teams. This classification is also reported automatically to the user and saved in a database.</p>

    <p style="text-align: justify">You may consult the original project information <a class = "a-app" href="http://medicalresearch.inescporto.pt/breastresearch/index.php/BCCT.core" target="_blank">here</a>.</p>
{% endblock content %}

docker/bcctapp/templates/bcctapp/contact.html
{% extends "bcctapp/base.html" %}
{% load crispy_forms_tags %}

{% block extra_style %}
<style>

    /*star rating style based on render*/
    .star-rating li {
        display: inline-block !important;
        padding:0;
        margin:0;
        color:rgb(148, 145, 145);
        text-shadow: 2px 2px 5px grey;
        font-size: 2.7rem;
    }

    .star-rating li label::after {
        content: "\2605";
        padding:0;
        margin:0;
    }

    .star-rating ul {
        padding:0;
        margin:0;
    }

    .star-rating ul li:hover
    {
        color:yellow;
    }

    .star-rating li.active, .star-rating li.secondary-active {
        color:yellow;
    }

    .star-rating label {
        display: inline-block;
        border-radius: 3px;
        position: relative;
        padding:0;
        margin:0;
    }

    .star-rating label::before {
        padding:0;
        margin:0;
    }
    
    .star-rating input[type=radio] {
        opacity: 1;
	    position: absolute;
        z-index: -1;
        top:50%;
        left:40%;
    }

    .star-rating input[type=radio]:checked +label {
         border: 1px solid blue;
    }


    .star-rating li.hover-stars {
        color: rgb(238, 238, 161);
    }

    .star-rating li.prev-stars {
        color:yellow;
    }

</style>

{% endblock extra_style %}

{% block content %}

<nav class = "m-2">
    <ol class="cd-breadcrumb w-100">
        {% if user.is_authenticated %}
        <li>Logged in</li>
        {% endif %}
        <li class = "current"><a class = "no-underline" href="#">Feedback</a></li>
    </ol>
</nav>

<h1 class = "m-2">Give us some feedback</h1>

<form method="POST">
    {% csrf_token %}
    <div class="form-row">
        <div title = "Enter your email" class="form-group col-md-6 mb-0">
          {{ form.email|as_crispy_field }}
        </div>
        <div title = "Enter your username" class="form-group col-md-6 mb-0">
          {{ form.name|as_crispy_field }}
        </div>
    </div>
    <div title = "Give us some feedback">
        {{form.content|as_crispy_field}}
    </div>
    

    <div title = "Gives us a rating" id="div_id_score" class = "star-rating form-group">
        <label for="id_score" class="col-form-label requiredField">
            Score<span class="asteriskField">*</span>
        </label>
        {{form.score}}
    </div>


    <button type="submit" class="btn-app px-2 py-1">Send email</button>
</form>

{% endblock content %}

{% block extra_js %}
<script>

    'use strict';
    
    const rating = document.querySelector('.star-rating');
    const stars = rating.querySelectorAll('li');

    function paintPreviousStars() {
        [...stars].forEach(star => star.addEventListener('click', function(e) {
            let current_selected = rating.querySelector('.active');

            if (current_selected !== null) {
                rating.querySelector('.active').classList.remove('active');

                [... rating.querySelectorAll('.secondary-active')].forEach(
                    e => e.classList.remove('secondary-active'));
            }

            star.classList.add('active');
            let element = star;

            while (element = element.previousElementSibling)
                element.classList.add('secondary-active');

        }));
    }

    function showDifferentStaronHover() {
        [...stars].forEach(star => star.addEventListener('mouseenter', function(e) {

            let traverse_prev = star;

            while(traverse_prev = traverse_prev.previousElementSibling) {
                traverse_prev.classList.add('prev-stars');
            }

            // add it
            let element = star;
            element.classList.add('hover-stars');
            while (element = element.nextElementSibling) {
                if (element.classList.contains('active') || element.classList.contains('secondary-active'))
                    element.classList.add('hover-stars');
                else break;    
            }
                
        }));
    }

    function removeHoverEffect() {
        [...stars].forEach(star => star.addEventListener('mouseout', function(e) {

            let hovered_stars = document.querySelectorAll('.star-rating .hover-stars');
            let prev_stars = document.querySelectorAll('.star-rating .prev-stars');

            if (hovered_stars !== null) 
                [...hovered_stars].forEach(e => e.classList.remove('hover-stars'));
            
            if (prev_stars !== null)
                [...prev_stars].forEach(e => e.classList.remove('prev-stars'));
        
        }));
    }

    (function() {
        paintPreviousStars();
        showDifferentStaronHover();
        removeHoverEffect();
    })();

</script>
{% endblock extra_js %}

docker/bcctapp/templates/bcctapp/medical_image_plot.html
{% extends "bcctapp/base.html" %}
{% block content %}
<div class="container">
        <div class="row" style="display: inline;">
              {% for elem in graph %}
                {{elem|safe}}
              {% endfor %}
        </div>
      </div>
{% endblock content %}

docker/bcctapp/templates/bcctapp/medical_images_list.html
{% extends "bcctapp/base.html" %}
{% block content %}
    <h2>{{ user }}'s Medical Images List</h2>
    <h2>{{ doctor }}'s Medical Images List</h2>
    <table class="table" id="table_1">
        <tbody>
            {% for image in medical_images %}
            {% if user == image.doctor %}
            <tr>
                <td><img src="{{ image.image.url }}" alt="Medical Image {{ image.pk }}"></td>
            </tr>
            <tr>
                <td><form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary" value="{{ image.pk }}" name="medical_image">Predict Image Keypoints!</button>
                    </form>
                    <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" style="margin-top: 5px" value="{{ image.pk }}" name="medical_image_to_delete">Delete!</button>
                    </form>
                    {% if image.keypoints %}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-info" style="margin-top: 5px" value="{{ image.pk }}" name="view_kpts">Plot Keypoints!</button>
                        </form>
                    {% endif %}
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

docker/bcctapp/templates/bcctapp/patient_confirm_delete.html
{% extends "bcctapp/base.html" %}
{% block content %}

<nav class = "mt-2 mb-4">
    <ol class="cd-breadcrumb w-100">
        {% if user.is_authenticated %}
        <li>Logged in</li>
        {% endif %}
        <li><a class = "no-underline" href="{%url 'patient-detail' patient.id %}">Patient</a></li>
        <li class = "current"><a class = "no-underline" href="#">Delete </a></li>
    </ol>
  </nav>

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> <span class = "text-primary-color">Delete Patient</span> with ID {{object.id}}</legend>
                <h2 class = "h3">Are you sure you want to delete the patient "{{ object.first_name }} {{object.last_name}}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete!</button>
                <a class="btn btn-outline-secondary" href="{% url 'patient-detail' object.id %}">Cancel!</a>
            </div>
        </form>
    </div>
{% endblock content %}

docker/bcctapp/templates/bcctapp/post.html
{% extends "bcctapp/base.html" %}
{% block content %}
    <h2>Upload</h2>
   <form id="post_form" method="post" action="" enctype="multipart/form-data">

    {% csrf_token %}
    {% for hidden in postForm.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in postForm %}
        {{ field }} <br />
    {% endfor %}

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}


    <input type="submit" name="submit" value="Submit" />
</form>
{% endblock content %}

docker/bcctapp/templates/bcctapp/post_request.html
{% extends "bcctapp/base.html" %}
{% block content %}
   <h1>Cinderella Application Demo</h1>
  <form id="form" method="POST">
    {% csrf_token %}

      <label for="image">image:</label><br>
      <input type="file" id="image" name="image"  accept="image/*" multiple>
      <input type="submit">

      <label for="first_name">first_name (yr):</label><br>
      <input type="text" id="first_name" name="first_name" value="1" min="1" max="150" required>


  </form>


{% endblock content %}